version: "3"
services:

  frontend:
    build: .
    container_name: frontend
    restart: always
    environment:
      - REACT_APP_API_KEY=${REACT_APP_API_KEY}
      - REACT_APP_API_BASE_URL=${REACT_APP_API_BASE_URL}
    ports:
      - "3000:3000"
