version: '3.9'

services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_KEY=${REACT_APP_API_KEY}
      - REACT_APP_API_BASE_URL=${REACT_APP_API_BASE_URL}
    volumes:
      - .:/app
      - /app/node_modules
